// Code generated by ent, DO NOT EDIT.

package collectspec

import (
	"stacksviz/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CollectSpec {
	return predicate.CollectSpec(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CollectSpec {
	return predicate.CollectSpec(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CollectSpec {
	return predicate.CollectSpec(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CollectSpec {
	return predicate.CollectSpec(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CollectSpec {
	return predicate.CollectSpec(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CollectSpec {
	return predicate.CollectSpec(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CollectSpec {
	return predicate.CollectSpec(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CollectSpec {
	return predicate.CollectSpec(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CollectSpec {
	return predicate.CollectSpec(sql.FieldLTE(FieldID, id))
}

// HasFrames applies the HasEdge predicate on the "frames" edge.
func HasFrames() predicate.CollectSpec {
	return predicate.CollectSpec(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FramesTable, FramesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFramesWith applies the HasEdge predicate on the "frames" edge with a given conditions (other predicates).
func HasFramesWith(preds ...predicate.FrameInfo) predicate.CollectSpec {
	return predicate.CollectSpec(func(s *sql.Selector) {
		step := newFramesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CollectSpec) predicate.CollectSpec {
	return predicate.CollectSpec(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CollectSpec) predicate.CollectSpec {
	return predicate.CollectSpec(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CollectSpec) predicate.CollectSpec {
	return predicate.CollectSpec(func(s *sql.Selector) {
		p(s.Not())
	})
}
