// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"stacksviz/ent/collection"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Collection is the model entity for the Collection schema.
type Collection struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CollectionQuery when eager-loading is set.
	Edges        CollectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CollectionEdges holds the relations/edges for other nodes in the graph.
type CollectionEdges struct {
	// ProcessSnapshots holds the value of the process_snapshots edge.
	ProcessSnapshots []*ProcessSnapshot `json:"process_snapshots,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedProcessSnapshots map[string][]*ProcessSnapshot
}

// ProcessSnapshotsOrErr returns the ProcessSnapshots value or an error if the edge
// was not loaded in eager-loading.
func (e CollectionEdges) ProcessSnapshotsOrErr() ([]*ProcessSnapshot, error) {
	if e.loadedTypes[0] {
		return e.ProcessSnapshots, nil
	}
	return nil, &NotLoadedError{edge: "process_snapshots"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Collection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case collection.FieldID:
			values[i] = new(sql.NullInt64)
		case collection.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Collection fields.
func (c *Collection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case collection.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case collection.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Collection.
// This includes values selected through modifiers, order, etc.
func (c *Collection) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryProcessSnapshots queries the "process_snapshots" edge of the Collection entity.
func (c *Collection) QueryProcessSnapshots() *ProcessSnapshotQuery {
	return NewCollectionClient(c.config).QueryProcessSnapshots(c)
}

// Update returns a builder for updating this Collection.
// Note that you need to call Collection.Unwrap() before calling this method if this Collection
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Collection) Update() *CollectionUpdateOne {
	return NewCollectionClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Collection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Collection) Unwrap() *Collection {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Collection is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Collection) String() string {
	var builder strings.Builder
	builder.WriteString("Collection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("name=")
	builder.WriteString(c.Name)
	builder.WriteByte(')')
	return builder.String()
}

// NamedProcessSnapshots returns the ProcessSnapshots named value or an error if the edge was not
// loaded in eager-loading with this name.
func (c *Collection) NamedProcessSnapshots(name string) ([]*ProcessSnapshot, error) {
	if c.Edges.namedProcessSnapshots == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := c.Edges.namedProcessSnapshots[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (c *Collection) appendNamedProcessSnapshots(name string, edges ...*ProcessSnapshot) {
	if c.Edges.namedProcessSnapshots == nil {
		c.Edges.namedProcessSnapshots = make(map[string][]*ProcessSnapshot)
	}
	if len(edges) == 0 {
		c.Edges.namedProcessSnapshots[name] = []*ProcessSnapshot{}
	} else {
		c.Edges.namedProcessSnapshots[name] = append(c.Edges.namedProcessSnapshots[name], edges...)
	}
}

// Collections is a parsable slice of Collection.
type Collections []*Collection
