// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"stacksviz/ent/collectspec"
	"stacksviz/ent/framespec"
	"stacksviz/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// FrameSpecUpdate is the builder for updating FrameSpec entities.
type FrameSpecUpdate struct {
	config
	hooks    []Hook
	mutation *FrameSpecMutation
}

// Where appends a list predicates to the FrameSpecUpdate builder.
func (fsu *FrameSpecUpdate) Where(ps ...predicate.FrameSpec) *FrameSpecUpdate {
	fsu.mutation.Where(ps...)
	return fsu
}

// SetFrame sets the "frame" field.
func (fsu *FrameSpecUpdate) SetFrame(s string) *FrameSpecUpdate {
	fsu.mutation.SetFrame(s)
	return fsu
}

// SetCollectSpec sets the "collect_spec" field.
func (fsu *FrameSpecUpdate) SetCollectSpec(i int) *FrameSpecUpdate {
	fsu.mutation.SetCollectSpec(i)
	return fsu
}

// SetCollectExpressions sets the "collect_expressions" field.
func (fsu *FrameSpecUpdate) SetCollectExpressions(s []string) *FrameSpecUpdate {
	fsu.mutation.SetCollectExpressions(s)
	return fsu
}

// AppendCollectExpressions appends s to the "collect_expressions" field.
func (fsu *FrameSpecUpdate) AppendCollectExpressions(s []string) *FrameSpecUpdate {
	fsu.mutation.AppendCollectExpressions(s)
	return fsu
}

// SetFlightRecorderEvents sets the "flight_recorder_events" field.
func (fsu *FrameSpecUpdate) SetFlightRecorderEvents(s []string) *FrameSpecUpdate {
	fsu.mutation.SetFlightRecorderEvents(s)
	return fsu
}

// AppendFlightRecorderEvents appends s to the "flight_recorder_events" field.
func (fsu *FrameSpecUpdate) AppendFlightRecorderEvents(s []string) *FrameSpecUpdate {
	fsu.mutation.AppendFlightRecorderEvents(s)
	return fsu
}

// SetCollectSpecRefID sets the "collect_spec_ref" edge to the CollectSpec entity by ID.
func (fsu *FrameSpecUpdate) SetCollectSpecRefID(id int) *FrameSpecUpdate {
	fsu.mutation.SetCollectSpecRefID(id)
	return fsu
}

// SetCollectSpecRef sets the "collect_spec_ref" edge to the CollectSpec entity.
func (fsu *FrameSpecUpdate) SetCollectSpecRef(c *CollectSpec) *FrameSpecUpdate {
	return fsu.SetCollectSpecRefID(c.ID)
}

// Mutation returns the FrameSpecMutation object of the builder.
func (fsu *FrameSpecUpdate) Mutation() *FrameSpecMutation {
	return fsu.mutation
}

// ClearCollectSpecRef clears the "collect_spec_ref" edge to the CollectSpec entity.
func (fsu *FrameSpecUpdate) ClearCollectSpecRef() *FrameSpecUpdate {
	fsu.mutation.ClearCollectSpecRef()
	return fsu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fsu *FrameSpecUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fsu.sqlSave, fsu.mutation, fsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fsu *FrameSpecUpdate) SaveX(ctx context.Context) int {
	affected, err := fsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fsu *FrameSpecUpdate) Exec(ctx context.Context) error {
	_, err := fsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsu *FrameSpecUpdate) ExecX(ctx context.Context) {
	if err := fsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fsu *FrameSpecUpdate) check() error {
	if _, ok := fsu.mutation.CollectSpecRefID(); fsu.mutation.CollectSpecRefCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "FrameSpec.collect_spec_ref"`)
	}
	return nil
}

func (fsu *FrameSpecUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(framespec.Table, framespec.Columns, sqlgraph.NewFieldSpec(framespec.FieldID, field.TypeInt))
	if ps := fsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fsu.mutation.Frame(); ok {
		_spec.SetField(framespec.FieldFrame, field.TypeString, value)
	}
	if value, ok := fsu.mutation.CollectExpressions(); ok {
		_spec.SetField(framespec.FieldCollectExpressions, field.TypeJSON, value)
	}
	if value, ok := fsu.mutation.AppendedCollectExpressions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, framespec.FieldCollectExpressions, value)
		})
	}
	if value, ok := fsu.mutation.FlightRecorderEvents(); ok {
		_spec.SetField(framespec.FieldFlightRecorderEvents, field.TypeJSON, value)
	}
	if value, ok := fsu.mutation.AppendedFlightRecorderEvents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, framespec.FieldFlightRecorderEvents, value)
		})
	}
	if fsu.mutation.CollectSpecRefCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   framespec.CollectSpecRefTable,
			Columns: []string{framespec.CollectSpecRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectspec.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fsu.mutation.CollectSpecRefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   framespec.CollectSpecRefTable,
			Columns: []string{framespec.CollectSpecRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectspec.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{framespec.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fsu.mutation.done = true
	return n, nil
}

// FrameSpecUpdateOne is the builder for updating a single FrameSpec entity.
type FrameSpecUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FrameSpecMutation
}

// SetFrame sets the "frame" field.
func (fsuo *FrameSpecUpdateOne) SetFrame(s string) *FrameSpecUpdateOne {
	fsuo.mutation.SetFrame(s)
	return fsuo
}

// SetCollectSpec sets the "collect_spec" field.
func (fsuo *FrameSpecUpdateOne) SetCollectSpec(i int) *FrameSpecUpdateOne {
	fsuo.mutation.SetCollectSpec(i)
	return fsuo
}

// SetCollectExpressions sets the "collect_expressions" field.
func (fsuo *FrameSpecUpdateOne) SetCollectExpressions(s []string) *FrameSpecUpdateOne {
	fsuo.mutation.SetCollectExpressions(s)
	return fsuo
}

// AppendCollectExpressions appends s to the "collect_expressions" field.
func (fsuo *FrameSpecUpdateOne) AppendCollectExpressions(s []string) *FrameSpecUpdateOne {
	fsuo.mutation.AppendCollectExpressions(s)
	return fsuo
}

// SetFlightRecorderEvents sets the "flight_recorder_events" field.
func (fsuo *FrameSpecUpdateOne) SetFlightRecorderEvents(s []string) *FrameSpecUpdateOne {
	fsuo.mutation.SetFlightRecorderEvents(s)
	return fsuo
}

// AppendFlightRecorderEvents appends s to the "flight_recorder_events" field.
func (fsuo *FrameSpecUpdateOne) AppendFlightRecorderEvents(s []string) *FrameSpecUpdateOne {
	fsuo.mutation.AppendFlightRecorderEvents(s)
	return fsuo
}

// SetCollectSpecRefID sets the "collect_spec_ref" edge to the CollectSpec entity by ID.
func (fsuo *FrameSpecUpdateOne) SetCollectSpecRefID(id int) *FrameSpecUpdateOne {
	fsuo.mutation.SetCollectSpecRefID(id)
	return fsuo
}

// SetCollectSpecRef sets the "collect_spec_ref" edge to the CollectSpec entity.
func (fsuo *FrameSpecUpdateOne) SetCollectSpecRef(c *CollectSpec) *FrameSpecUpdateOne {
	return fsuo.SetCollectSpecRefID(c.ID)
}

// Mutation returns the FrameSpecMutation object of the builder.
func (fsuo *FrameSpecUpdateOne) Mutation() *FrameSpecMutation {
	return fsuo.mutation
}

// ClearCollectSpecRef clears the "collect_spec_ref" edge to the CollectSpec entity.
func (fsuo *FrameSpecUpdateOne) ClearCollectSpecRef() *FrameSpecUpdateOne {
	fsuo.mutation.ClearCollectSpecRef()
	return fsuo
}

// Where appends a list predicates to the FrameSpecUpdate builder.
func (fsuo *FrameSpecUpdateOne) Where(ps ...predicate.FrameSpec) *FrameSpecUpdateOne {
	fsuo.mutation.Where(ps...)
	return fsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fsuo *FrameSpecUpdateOne) Select(field string, fields ...string) *FrameSpecUpdateOne {
	fsuo.fields = append([]string{field}, fields...)
	return fsuo
}

// Save executes the query and returns the updated FrameSpec entity.
func (fsuo *FrameSpecUpdateOne) Save(ctx context.Context) (*FrameSpec, error) {
	return withHooks(ctx, fsuo.sqlSave, fsuo.mutation, fsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fsuo *FrameSpecUpdateOne) SaveX(ctx context.Context) *FrameSpec {
	node, err := fsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fsuo *FrameSpecUpdateOne) Exec(ctx context.Context) error {
	_, err := fsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fsuo *FrameSpecUpdateOne) ExecX(ctx context.Context) {
	if err := fsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fsuo *FrameSpecUpdateOne) check() error {
	if _, ok := fsuo.mutation.CollectSpecRefID(); fsuo.mutation.CollectSpecRefCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "FrameSpec.collect_spec_ref"`)
	}
	return nil
}

func (fsuo *FrameSpecUpdateOne) sqlSave(ctx context.Context) (_node *FrameSpec, err error) {
	if err := fsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(framespec.Table, framespec.Columns, sqlgraph.NewFieldSpec(framespec.FieldID, field.TypeInt))
	id, ok := fsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FrameSpec.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, framespec.FieldID)
		for _, f := range fields {
			if !framespec.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != framespec.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fsuo.mutation.Frame(); ok {
		_spec.SetField(framespec.FieldFrame, field.TypeString, value)
	}
	if value, ok := fsuo.mutation.CollectExpressions(); ok {
		_spec.SetField(framespec.FieldCollectExpressions, field.TypeJSON, value)
	}
	if value, ok := fsuo.mutation.AppendedCollectExpressions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, framespec.FieldCollectExpressions, value)
		})
	}
	if value, ok := fsuo.mutation.FlightRecorderEvents(); ok {
		_spec.SetField(framespec.FieldFlightRecorderEvents, field.TypeJSON, value)
	}
	if value, ok := fsuo.mutation.AppendedFlightRecorderEvents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, framespec.FieldFlightRecorderEvents, value)
		})
	}
	if fsuo.mutation.CollectSpecRefCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   framespec.CollectSpecRefTable,
			Columns: []string{framespec.CollectSpecRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectspec.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fsuo.mutation.CollectSpecRefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   framespec.CollectSpecRefTable,
			Columns: []string{framespec.CollectSpecRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectspec.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FrameSpec{config: fsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{framespec.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fsuo.mutation.done = true
	return _node, nil
}
