// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"stacksviz/ent/framespec"
	"stacksviz/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FrameSpecDelete is the builder for deleting a FrameSpec entity.
type FrameSpecDelete struct {
	config
	hooks    []Hook
	mutation *FrameSpecMutation
}

// Where appends a list predicates to the FrameSpecDelete builder.
func (fsd *FrameSpecDelete) Where(ps ...predicate.FrameSpec) *FrameSpecDelete {
	fsd.mutation.Where(ps...)
	return fsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fsd *FrameSpecDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fsd.sqlExec, fsd.mutation, fsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fsd *FrameSpecDelete) ExecX(ctx context.Context) int {
	n, err := fsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fsd *FrameSpecDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(framespec.Table, sqlgraph.NewFieldSpec(framespec.FieldID, field.TypeInt))
	if ps := fsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fsd.mutation.done = true
	return affected, err
}

// FrameSpecDeleteOne is the builder for deleting a single FrameSpec entity.
type FrameSpecDeleteOne struct {
	fsd *FrameSpecDelete
}

// Where appends a list predicates to the FrameSpecDelete builder.
func (fsdo *FrameSpecDeleteOne) Where(ps ...predicate.FrameSpec) *FrameSpecDeleteOne {
	fsdo.fsd.mutation.Where(ps...)
	return fsdo
}

// Exec executes the deletion query.
func (fsdo *FrameSpecDeleteOne) Exec(ctx context.Context) error {
	n, err := fsdo.fsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{framespec.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fsdo *FrameSpecDeleteOne) ExecX(ctx context.Context) {
	if err := fsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
