// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (c *Collection) ProcessSnapshots(ctx context.Context) (result []*ProcessSnapshot, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = c.NamedProcessSnapshots(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = c.Edges.ProcessSnapshotsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = c.QueryProcessSnapshots().All(ctx)
	}
	return result, err
}
