// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"stacksviz/ent/predicate"
	"stacksviz/ent/processsnapshot"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ProcessSnapshotUpdate is the builder for updating ProcessSnapshot entities.
type ProcessSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *ProcessSnapshotMutation
}

// Where appends a list predicates to the ProcessSnapshotUpdate builder.
func (psu *ProcessSnapshotUpdate) Where(ps ...predicate.ProcessSnapshot) *ProcessSnapshotUpdate {
	psu.mutation.Where(ps...)
	return psu
}

// SetProcessID sets the "process_id" field.
func (psu *ProcessSnapshotUpdate) SetProcessID(s string) *ProcessSnapshotUpdate {
	psu.mutation.SetProcessID(s)
	return psu
}

// SetSnapshot sets the "snapshot" field.
func (psu *ProcessSnapshotUpdate) SetSnapshot(s string) *ProcessSnapshotUpdate {
	psu.mutation.SetSnapshot(s)
	return psu
}

// SetFramesOfInterest sets the "frames_of_interest" field.
func (psu *ProcessSnapshotUpdate) SetFramesOfInterest(s []string) *ProcessSnapshotUpdate {
	psu.mutation.SetFramesOfInterest(s)
	return psu
}

// AppendFramesOfInterest appends s to the "frames_of_interest" field.
func (psu *ProcessSnapshotUpdate) AppendFramesOfInterest(s []string) *ProcessSnapshotUpdate {
	psu.mutation.AppendFramesOfInterest(s)
	return psu
}

// ClearFramesOfInterest clears the value of the "frames_of_interest" field.
func (psu *ProcessSnapshotUpdate) ClearFramesOfInterest() *ProcessSnapshotUpdate {
	psu.mutation.ClearFramesOfInterest()
	return psu
}

// Mutation returns the ProcessSnapshotMutation object of the builder.
func (psu *ProcessSnapshotUpdate) Mutation() *ProcessSnapshotMutation {
	return psu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (psu *ProcessSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, psu.sqlSave, psu.mutation, psu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psu *ProcessSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := psu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (psu *ProcessSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := psu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psu *ProcessSnapshotUpdate) ExecX(ctx context.Context) {
	if err := psu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psu *ProcessSnapshotUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(processsnapshot.Table, processsnapshot.Columns, sqlgraph.NewFieldSpec(processsnapshot.FieldID, field.TypeInt))
	if ps := psu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psu.mutation.ProcessID(); ok {
		_spec.SetField(processsnapshot.FieldProcessID, field.TypeString, value)
	}
	if value, ok := psu.mutation.Snapshot(); ok {
		_spec.SetField(processsnapshot.FieldSnapshot, field.TypeString, value)
	}
	if value, ok := psu.mutation.FramesOfInterest(); ok {
		_spec.SetField(processsnapshot.FieldFramesOfInterest, field.TypeJSON, value)
	}
	if value, ok := psu.mutation.AppendedFramesOfInterest(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, processsnapshot.FieldFramesOfInterest, value)
		})
	}
	if psu.mutation.FramesOfInterestCleared() {
		_spec.ClearField(processsnapshot.FieldFramesOfInterest, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, psu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	psu.mutation.done = true
	return n, nil
}

// ProcessSnapshotUpdateOne is the builder for updating a single ProcessSnapshot entity.
type ProcessSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcessSnapshotMutation
}

// SetProcessID sets the "process_id" field.
func (psuo *ProcessSnapshotUpdateOne) SetProcessID(s string) *ProcessSnapshotUpdateOne {
	psuo.mutation.SetProcessID(s)
	return psuo
}

// SetSnapshot sets the "snapshot" field.
func (psuo *ProcessSnapshotUpdateOne) SetSnapshot(s string) *ProcessSnapshotUpdateOne {
	psuo.mutation.SetSnapshot(s)
	return psuo
}

// SetFramesOfInterest sets the "frames_of_interest" field.
func (psuo *ProcessSnapshotUpdateOne) SetFramesOfInterest(s []string) *ProcessSnapshotUpdateOne {
	psuo.mutation.SetFramesOfInterest(s)
	return psuo
}

// AppendFramesOfInterest appends s to the "frames_of_interest" field.
func (psuo *ProcessSnapshotUpdateOne) AppendFramesOfInterest(s []string) *ProcessSnapshotUpdateOne {
	psuo.mutation.AppendFramesOfInterest(s)
	return psuo
}

// ClearFramesOfInterest clears the value of the "frames_of_interest" field.
func (psuo *ProcessSnapshotUpdateOne) ClearFramesOfInterest() *ProcessSnapshotUpdateOne {
	psuo.mutation.ClearFramesOfInterest()
	return psuo
}

// Mutation returns the ProcessSnapshotMutation object of the builder.
func (psuo *ProcessSnapshotUpdateOne) Mutation() *ProcessSnapshotMutation {
	return psuo.mutation
}

// Where appends a list predicates to the ProcessSnapshotUpdate builder.
func (psuo *ProcessSnapshotUpdateOne) Where(ps ...predicate.ProcessSnapshot) *ProcessSnapshotUpdateOne {
	psuo.mutation.Where(ps...)
	return psuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (psuo *ProcessSnapshotUpdateOne) Select(field string, fields ...string) *ProcessSnapshotUpdateOne {
	psuo.fields = append([]string{field}, fields...)
	return psuo
}

// Save executes the query and returns the updated ProcessSnapshot entity.
func (psuo *ProcessSnapshotUpdateOne) Save(ctx context.Context) (*ProcessSnapshot, error) {
	return withHooks(ctx, psuo.sqlSave, psuo.mutation, psuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psuo *ProcessSnapshotUpdateOne) SaveX(ctx context.Context) *ProcessSnapshot {
	node, err := psuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (psuo *ProcessSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := psuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psuo *ProcessSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := psuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psuo *ProcessSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *ProcessSnapshot, err error) {
	_spec := sqlgraph.NewUpdateSpec(processsnapshot.Table, processsnapshot.Columns, sqlgraph.NewFieldSpec(processsnapshot.FieldID, field.TypeInt))
	id, ok := psuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProcessSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := psuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processsnapshot.FieldID)
		for _, f := range fields {
			if !processsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != processsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := psuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psuo.mutation.ProcessID(); ok {
		_spec.SetField(processsnapshot.FieldProcessID, field.TypeString, value)
	}
	if value, ok := psuo.mutation.Snapshot(); ok {
		_spec.SetField(processsnapshot.FieldSnapshot, field.TypeString, value)
	}
	if value, ok := psuo.mutation.FramesOfInterest(); ok {
		_spec.SetField(processsnapshot.FieldFramesOfInterest, field.TypeJSON, value)
	}
	if value, ok := psuo.mutation.AppendedFramesOfInterest(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, processsnapshot.FieldFramesOfInterest, value)
		})
	}
	if psuo.mutation.FramesOfInterestCleared() {
		_spec.ClearField(processsnapshot.FieldFramesOfInterest, field.TypeJSON)
	}
	_node = &ProcessSnapshot{config: psuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, psuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	psuo.mutation.done = true
	return _node, nil
}
