// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"stacksviz/ent/predicate"
	"stacksviz/ent/processsnapshot"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProcessSnapshotDelete is the builder for deleting a ProcessSnapshot entity.
type ProcessSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *ProcessSnapshotMutation
}

// Where appends a list predicates to the ProcessSnapshotDelete builder.
func (psd *ProcessSnapshotDelete) Where(ps ...predicate.ProcessSnapshot) *ProcessSnapshotDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *ProcessSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *ProcessSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *ProcessSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(processsnapshot.Table, sqlgraph.NewFieldSpec(processsnapshot.FieldID, field.TypeInt64))
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// ProcessSnapshotDeleteOne is the builder for deleting a single ProcessSnapshot entity.
type ProcessSnapshotDeleteOne struct {
	psd *ProcessSnapshotDelete
}

// Where appends a list predicates to the ProcessSnapshotDelete builder.
func (psdo *ProcessSnapshotDeleteOne) Where(ps ...predicate.ProcessSnapshot) *ProcessSnapshotDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *ProcessSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{processsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *ProcessSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
