// Code generated by ent, DO NOT EDIT.

package ent

import (
	"stacksviz/ent/collection"
	"stacksviz/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	collectionFields := schema.Collection{}.Fields()
	_ = collectionFields
	// collectionDescID is the schema descriptor for id field.
	collectionDescID := collectionFields[0].Descriptor()
	// collection.IDValidator is a validator for the "id" field. It is called by the builders before save.
	collection.IDValidator = collectionDescID.Validators[0].(func(int) error)
}
