// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CollectSpec is the predicate function for collectspec builders.
type CollectSpec func(*sql.Selector)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// FrameInfo is the predicate function for frameinfo builders.
type FrameInfo func(*sql.Selector)

// ProcessSnapshot is the predicate function for processsnapshot builders.
type ProcessSnapshot func(*sql.Selector)
