// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// ProcessSnapshot is the predicate function for processsnapshot builders.
type ProcessSnapshot func(*sql.Selector)
