package server

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"stacksviz/ent"
	"stacksviz/ent/collection"
	"stacksviz/ent/framespec"
	"stacksviz/graph"
	"stacksviz/stacks"
	"time"

	pp "github.com/maruel/panicparse/v2/stack"
	"golang.org/x/sync/errgroup"
)

// CollectCollection is the resolver for the collectCollection field.
func (r *mutationResolver) CollectCollection(ctx context.Context) (*ent.Collection, error) {
	dbClient := ent.FromContext(ctx)
	i := 0
	psIDs := make([]int, 0, len(r.conf.Targets))

	// Read the name of the first (and only) service.
	if len(r.conf.Targets) != 1 {
		return nil, fmt.Errorf("expected exactly one service")
	}

	var svcName string
	for serviceName, _ := range r.conf.Targets {
		// TODO(andrei): deal with multiple services
		svcName = serviceName
	}

	var g errgroup.Group
	spec := getOrCreateCollectSpec(ctx, dbClient)
	for processName, url := range r.conf.Targets[svcName] {
		i++
		processName := processName
		url := url
		g.Go(func() error {
			log.Printf("collecting snapshot from process %d: %s-%s - %s", i, svcName, processName, url)
			// !!! snap, err := r.getSnapshotFromPprof(url)
			snap, err := r.getSnapshotFromDelveAgent(ctx, url, spec)
			if err != nil {
				return err
			}
			log.Printf("!!! delve agent returned")
			var framesOfInterest string
			if len(snap.FramesOfInterest) > 0 {
				b, err := json.Marshal(snap.FramesOfInterest)
				if err != nil {
					return err
				}
				framesOfInterest = string(b)
			}

			log.Printf("!!! creating snapshot with frames of interest: %s", framesOfInterest)
			input := ent.CreateProcessSnapshotInput{
				ProcessID: processName,
				Snapshot:  snapToString(snap),
			}
			if framesOfInterest != "" {
				input.FramesOfInterest = &framesOfInterest
			}
			ps, err := dbClient.ProcessSnapshot.Create().SetInput(input).Save(ctx)
			if err != nil {
				return err
			}
			psIDs = append(psIDs, ps.ID)
			return nil
		})
	}
	if err := g.Wait(); err != nil {
		return nil, err
	}

	const timeFormat = "Monday, 02-Jan-06 15:04:05 MST"
	return dbClient.Collection.Create().
		SetName(fmt.Sprintf("%s - %s", svcName, time.Now().Format(timeFormat))).
		SetCollectSpec(spec.ID).
		AddProcessSnapshotIDs(psIDs...).
		Save(ctx)
}

// AddExprToCollectSpec is the resolver for the addExprToCollectSpec mutation.
func (r *mutationResolver) AddExprToCollectSpec(ctx context.Context, frame string, expr string) (_ *ent.CollectSpec, _err error) {
	dbClient := ent.FromContext(ctx)
	log.Printf("!!! AddExprToCollectSpec: starting")
	defer func() {
		log.Printf("!!! AddExprToCollectSpec: done")
	}()

	collectSpec := getOrCreateCollectSpec(ctx, dbClient)
	// Create of update the frame info.
	fi, err := collectSpec.QueryFrames().Where(framespec.Frame(frame)).Only(ctx)
	nfe := &ent.NotFoundError{}
	if errors.As(err, &nfe) {
		// Create a new FrameSpec with the given expression.
		fi = dbClient.FrameSpec.Create().
			SetParentCollection(collectSpec).
			SetFrame(frame).
			SetCollectExpressions([]string{expr}).
			SetFlightRecorderEvents([]string{}).
			SaveX(ctx)
		// !!! collectSpec = collectSpec.Update().AddFrames(fi).SaveX(ctx)
		return collectSpec, nil
	}
	if err != nil {
		return nil, err
	}
	for _, e := range fi.CollectExpressions {
		if e == expr {
			return collectSpec, nil
		}
	}
	fi.Update().SetCollectExpressions(append(fi.CollectExpressions, expr)).SaveX(ctx)
	return collectSpec, nil
}

// RemoveExprFromCollectSpec is the resolver for the removeExprFromCollectSpec field.
func (r *mutationResolver) RemoveExprFromCollectSpec(ctx context.Context, expr string, frame string) (*ent.CollectSpec, error) {
	log.Printf("!!! RemoveExprFromCollectSpec resolver")
	dbClient := ent.FromContext(ctx)
	collectSpec := getOrCreateCollectSpec(ctx, dbClient)
	fi, err := collectSpec.QueryFrames().Where(framespec.Frame(frame)).Only(ctx)
	nfe := &ent.NotFoundError{}
	if errors.As(err, &nfe) {
		return collectSpec, nil
	}
	foundIndex := -1
	for i, e := range fi.CollectExpressions {
		if e == expr {
			foundIndex = i
			break
		}
	}
	if foundIndex != -1 {
		fi.Update().SetCollectExpressions(append(fi.CollectExpressions[:foundIndex], fi.CollectExpressions[foundIndex+1:]...)).SaveX(ctx)
	}
	return collectSpec, nil
}

// AddFlightRecorderEventToCollectSpec is the resolver for the addFlightRecorderEventToCollectSpec field.
func (r *mutationResolver) AddFlightRecorderEventToCollectSpec(ctx context.Context, frame string, spec string) (_ *ent.CollectSpec, _err error) {
	dbClient := ent.FromContext(ctx)
	tx, err := dbClient.Tx(ctx)
	if err != nil {
		return nil, err
	}
	defer func() {
		if _err != nil {
			tx.Rollback()
		}
	}()

	collectSpec := getOrCreateCollectSpec(ctx, tx.Client())
	// Create of update the frame info.
	fi, err := collectSpec.QueryFrames().Where(framespec.Frame(frame)).Only(ctx)
	nfe := &ent.NotFoundError{}
	if errors.As(err, &nfe) {
		fi = tx.FrameSpec.Create().SetFrame(frame).SetFlightRecorderEvents([]string{spec}).SaveX(ctx)
		collectSpec = collectSpec.Update().AddFrames(fi).SaveX(ctx)
		if err := tx.Commit(); err != nil {
			return nil, err
		}
		return collectSpec, nil
	}
	if err != nil {
		return nil, err
	}
	for _, e := range fi.FlightRecorderEvents {
		if e == spec {
			return collectSpec, nil
		}
	}
	fi.Update().SetFlightRecorderEvents(append(fi.FlightRecorderEvents, spec)).SaveX(ctx)
	return collectSpec, nil
}

// RemoveFlightRecorderEventFromCollectSpec is the resolver for the removeFlightRecorderEventFromCollectSpec field.
func (r *mutationResolver) RemoveFlightRecorderEventFromCollectSpec(ctx context.Context, frame string, spec string) (*ent.CollectSpec, error) {
	log.Printf("!!! RemoveFlightRecorderEventFromCollectSpec resolver")
	dbClient := ent.FromContext(ctx)
	collectSpec := getOrCreateCollectSpec(ctx, dbClient)
	fi, err := collectSpec.QueryFrames().Where(framespec.Frame(frame)).Only(ctx)
	nfe := &ent.NotFoundError{}
	if errors.As(err, &nfe) {
		return collectSpec, nil
	}
	foundIndex := -1
	for i, e := range fi.FlightRecorderEvents {
		if e == spec {
			foundIndex = i
			break
		}
	}
	if foundIndex != -1 {
		fi.Update().SetFlightRecorderEvents(
			append(fi.CollectExpressions[:foundIndex], fi.CollectExpressions[foundIndex+1:]...),
		).SaveX(ctx)
	}
	return collectSpec, nil
}

// CollectionByID is the resolver for the collectionByID field.
func (r *queryResolver) CollectionByID(ctx context.Context, id int) (*ent.Collection, error) {
	log.Printf("!!! querying collection by ID: %d", id)
	dbClient := r.dbClient
	if dbClient == nil {
		panic("!!! nil client")
	}
	return dbClient.Collection.Query().Where(collection.ID(id)).Only(ctx)
}

// Goroutines is the resolver for the goroutines field.
func (r *queryResolver) Goroutines(ctx context.Context, colID int, snapID int, gID *int, filter *string) (*graph.SnapshotInfo, error) {
	log.Printf("!!! Goroutines resolver")
	snap, fois, err := r.stacksFetcher.Fetch(ctx, colID, snapID)
	if err != nil {
		return nil, err
	}
	snap = filterStacks(snap, gID, filter)
	agg := snap.Aggregate(pp.AnyValue)

	gMap := make(map[int]graph.GoroutineInfo, len(snap.Goroutines))
	for _, g := range snap.Goroutines {
		frames := make([]graph.FrameInfo, len(g.Stack.Calls))
		for j, c := range g.Stack.Calls {
			frames[j] = graph.FrameInfo{
				Func: c.Func.Complete,
				File: c.RemoteSrcPath,
				Line: c.Line,
			}
		}

		// Flatten all the collected variables, across all the frames.
		var flatVars []graph.CollectedVar
		for _, frames := range fois[g.ID] {
			flatVars = append(flatVars, frames.Vars...)
			// !!!
			//for _, v := range frames.Vars {
			//	flatVars = append(flatVars, graph.CollectedVar{
			//		Expr:  v.Expr,
			//		Value: v.Value,
			//		Links: stacks.LinksExcludingSelf(v.Links, g.ID),
			//	})
			//}
		}
		gMap[g.ID] = graph.GoroutineInfo{
			ID:     g.ID,
			Frames: frames,
			Vars:   flatVars,
		}
	}

	// !!!
	//if gID != nil {
	//	log.Printf("!!! filtering for goroutine: %d", *gID)
	//	if gi := gMap[*gID]; gi != nil {
	//		return &SnapshotInfo{
	//			Raw:        []*GoroutineInfo{gi},
	//			Aggregated: nil,
	//		}, nil
	//	}
	//	return nil, nil
	//} else {
	//	log.Printf("!!! not filtering for a specific goroutine")
	//}

	allGs := make([]graph.GoroutineInfo, 0, len(gMap))
	for _, gi := range gMap {
		allGs = append(allGs, gi)
	}

	groups := make([]graph.GoroutinesGroup, len(agg.Buckets))
	for i, b := range agg.Buckets {
		frames := make([]graph.FrameInfo, len(b.Stack.Calls))
		for j, c := range b.Stack.Calls {
			frames[j] = graph.FrameInfo{
				Func: c.Func.Complete,
				File: c.RemoteSrcPath,
				Line: c.Line,
			}
		}
		groups[i] = graph.GoroutinesGroup{
			IDs:    b.IDs,
			Frames: frames,
		}

		for _, gID := range b.IDs {
			if gi, ok := gMap[gID]; ok {
				groups[i].Vars = append(groups[i].Vars, gi.Vars...)
			}
		}
	}

	si := &graph.SnapshotInfo{
		Raw:        allGs,
		Aggregated: groups,
	}
	return si, nil
}

// AvailableVars is the resolver for the availableVars field.
func (r *queryResolver) AvailableVars(ctx context.Context, funcArg string, pcOff int) (*graph.VarsAndTypes, error) {
	log.Printf("!!! AvailableVars resolver")
	var svcName string
	for serviceName, _ := range r.conf.Targets {
		// TODO(andrei): deal with multiple services
		svcName = serviceName
	}

	var agentURL string
	for _, url := range r.conf.Targets[svcName] {
		agentURL = url
		break
	}

	log.Printf("!!! calling AvailableVars on Delve agent")
	vars, types, err := r.getAvailableVarsFromDelveAgent(agentURL, funcArg, int64(pcOff))
	if err != nil {
		return nil, err
	}
	resVars := make([]graph.VarInfo, len(vars))
	for i, v := range vars {
		resVars[i] = graph.VarInfo{
			Name:             v.Name,
			Type:             v.Type,
			FormalParameter:  v.FormalParameter,
			LoclistAvailable: v.LoclistAvailable,
		}
	}
	resTypes := make([]graph.TypeInfo, len(types))
	for i, t := range types {
		resTypes[i] = graph.TypeInfo{
			Name:            t.Name,
			FieldsNotLoaded: t.FieldsNotLoaded,
		}
		resTypes[i].Fields = make([]graph.FieldInfo, len(t.Fields))
		for j, f := range t.Fields {
			resTypes[i].Fields[j] = graph.FieldInfo{
				Name:     f.Name,
				Type:     f.TypeName,
				Embedded: f.Embedded,
			}
		}
	}

	res := &graph.VarsAndTypes{
		Vars:  resVars,
		Types: resTypes,
	}
	return res, nil
}

// CollectSpec is the resolver for the collectSpec field.
func (r *queryResolver) CollectSpec(ctx context.Context) (*ent.CollectSpec, error) {
	log.Printf("!!! CollectSpec resolver")
	dbClient := r.dbClient
	return dbClient.CollectSpec.Query().Only(ctx)
	//q := r.dbClient.FrameSpec.Query()
	//if funcArg != nil {
	//	q = q.Where(framespec.Frame(*funcArg))
	//}
	//res, err := q.All(ctx)
	//if err != nil {
	//	return nil, err
	//}
	//flat := make([]ent.FrameSpec, len(res))
	//for i := range res {
	//	flat[i] = *res[i]
	//}
	//return flat, nil
}

// TypeInfo is the resolver for the typeInfo field.
func (r *queryResolver) TypeInfo(ctx context.Context, name string) (*graph.TypeInfo, error) {
	log.Printf("!!! TypeInfo resolver")
	var svcName string
	for serviceName, _ := range r.conf.Targets {
		// TODO(andrei): deal with multiple services
		svcName = serviceName
	}

	var agentURL string
	for _, url := range r.conf.Targets[svcName] {
		agentURL = url
		break
	}

	fields, err := r.getTypeInfoFromDelveAgent(agentURL, name)
	if err != nil {
		return nil, err
	}
	return &graph.TypeInfo{
		Name:            name,
		Fields:          fields,
		FieldsNotLoaded: false,
	}, nil
}

// GetTree is the resolver for the getTree field.
func (r *queryResolver) GetTree(ctx context.Context, colID int, snapID int, gID *int, filter *string) (string, error) {
	log.Printf("!!! GetTree resolver")
	snap, fois, err := r.stacksFetcher.Fetch(ctx, colID, snapID)
	if err != nil {
		return "", err
	}
	snap = filterStacks(snap, gID, filter)
	tree := stacks.BuildTree(snap, fois)
	return tree.ToJSON(), nil
}

// FrameSpecsWhere is the resolver for the frameSpecsWhere field.
func (r *queryResolver) FrameSpecsWhere(ctx context.Context, where *ent.FrameSpecWhereInput) ([]ent.FrameSpec, error) {
	log.Printf("!!! FrameSpecsWhere: %+v", where)
	dbClient := r.dbClient
	pred, err := where.P()
	if err != nil {
		return nil, err
	}
	rows := dbClient.FrameSpec.Query().Where(pred).AllX(ctx)
	//if err != nil {
	//	return nil, err
	//}
	return flatten(rows), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
