// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CollectSpecsColumns holds the columns for the "collect_specs" table.
	CollectSpecsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// CollectSpecsTable holds the schema information for the "collect_specs" table.
	CollectSpecsTable = &schema.Table{
		Name:       "collect_specs",
		Columns:    CollectSpecsColumns,
		PrimaryKey: []*schema.Column{CollectSpecsColumns[0]},
	}
	// CollectionsColumns holds the columns for the "collections" table.
	CollectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "collect_spec", Type: field.TypeInt},
	}
	// CollectionsTable holds the schema information for the "collections" table.
	CollectionsTable = &schema.Table{
		Name:       "collections",
		Columns:    CollectionsColumns,
		PrimaryKey: []*schema.Column{CollectionsColumns[0]},
	}
	// FrameSpecsColumns holds the columns for the "frame_specs" table.
	FrameSpecsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "frame", Type: field.TypeString},
		{Name: "collect_expressions", Type: field.TypeJSON},
		{Name: "flight_recorder_events", Type: field.TypeJSON},
		{Name: "collect_spec_id", Type: field.TypeInt},
	}
	// FrameSpecsTable holds the schema information for the "frame_specs" table.
	FrameSpecsTable = &schema.Table{
		Name:       "frame_specs",
		Columns:    FrameSpecsColumns,
		PrimaryKey: []*schema.Column{FrameSpecsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "frame_specs_collect_specs_frames",
				Columns:    []*schema.Column{FrameSpecsColumns[4]},
				RefColumns: []*schema.Column{CollectSpecsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "framespec_collect_spec_id_frame",
				Unique:  false,
				Columns: []*schema.Column{FrameSpecsColumns[4], FrameSpecsColumns[1]},
			},
		},
	}
	// ProcessSnapshotsColumns holds the columns for the "process_snapshots" table.
	ProcessSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "process_id", Type: field.TypeString},
		{Name: "snapshot", Type: field.TypeString, Size: 2147483647},
		{Name: "frames_of_interest", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "collection_process_snapshots", Type: field.TypeInt, Nullable: true},
	}
	// ProcessSnapshotsTable holds the schema information for the "process_snapshots" table.
	ProcessSnapshotsTable = &schema.Table{
		Name:       "process_snapshots",
		Columns:    ProcessSnapshotsColumns,
		PrimaryKey: []*schema.Column{ProcessSnapshotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "process_snapshots_collections_process_snapshots",
				Columns:    []*schema.Column{ProcessSnapshotsColumns[4]},
				RefColumns: []*schema.Column{CollectionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CollectSpecsTable,
		CollectionsTable,
		FrameSpecsTable,
		ProcessSnapshotsTable,
	}
)

func init() {
	FrameSpecsTable.ForeignKeys[0].RefTable = CollectSpecsTable
	ProcessSnapshotsTable.ForeignKeys[0].RefTable = CollectionsTable
}
