// Code generated by ent, DO NOT EDIT.

package frameinfo

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the frameinfo type in the database.
	Label = "frame_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFrame holds the string denoting the frame field in the database.
	FieldFrame = "frame"
	// FieldExprs holds the string denoting the exprs field in the database.
	FieldExprs = "exprs"
	// Table holds the table name of the frameinfo in the database.
	Table = "frame_infos"
)

// Columns holds all SQL columns for frameinfo fields.
var Columns = []string{
	FieldID,
	FieldFrame,
	FieldExprs,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "frame_infos"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"collect_spec_frames",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the FrameInfo queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFrame orders the results by the frame field.
func ByFrame(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrame, opts...).ToFunc()
}
